version: "3.9"

networks:
  server:
    external: true

services:
  gitlabhackrlabs:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlabhackrlabs
    restart: always
    networks:
      server:
        aliases:
          - gitlabhackrlabs
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'